### ISSUE TITLE
What does the malicious activity look like?

### ISSUE THREAD

**Issue by iyadhalabi** [mvt-project/mvt#144]
Hi all..
So I had run the mvt-ios tool on two phones; one on Linux and one on Windows (more challenging but worked at the end). 
I was able to reach the final step and generate the JSON files against the STIX2 file provided. all the notfiications in the CMD/Konsol were informational and only few warnings (for a HTTP redirect to a different domain, but all seem legit).

Can I please know how to find the malicious processes and links on the resulted files (Wapp, Safarihistory, SMS.. etc) ? 
Shouldn't be a specific JSON file listing all the malicious activities if any was found?

I checked lots of videos and none was concerned about this last part.. how to asses the results without going into each JSON log and analyze them one at a time?!

Thanks

**Comment by botherder** [comment]
MVT does not detect malicious things in and of itself (with some minor per-module exceptions). Detection typically happens when you provide MVT with indicators of compromise (https://docs.mvt.re/en/latest/iocs.html). If you did that and no WARNING messages appeared and no *_detected.json file was created, it means there was nothing there to detect.
