### ISSUE TITLE
Other sources for STIX data

### ISSUE THREAD

**Issue by longeand** [mvt-project/mvt#265]
These github repositories have some STIX data that might be useful: 
1) in JSON STIX2.1 format: https://github.com/mitre-attack/attack-stix-data
2)same data in JSON STIX 2.0 format: https://github.com/mitre/cti
Not sure if these can be added to the command to download iocs so they are automatically included in the command to check backups for iocs also?
Thanks!

**Comment by botherder** [comment]
I might be wrong, but these STIX files don't seem to contain indicators. They seem to be STIX definition of ATT&CK-like capabilities mapping, along with some common malware definitions. These would not be usable for MVT, but I'm happy to re-assess if someone sees anything else. Admittedly, I did no check every single file in there, only a selection.

**Comment by Te-k** [comment]
I agree, I don't think they contain any actual indicator but mapping between MITRE ATTACK and groups, so not usable by MVT. Generally because we use forensic data for detect and because of the lack of definition of the STIX standard, I doubt we are going to find other STIX files directly usable by MVT.

I am closing the ticket, but feel free to suggest other source of IOCs we could use with MVT @longeand
