### ISSUE TITLE
Domain History - False Positive Results

### ISSUE THREAD

**Issue by jonathandata1** [mvt-project/mvt#319]
Because MVT-Tool is only IOCs in Safari History based on strings just by visiting the website on safari gives a false positive result. 

MVT-Tool delivers 2 different sets of results when presented with the same sample set. 

### Prep
open safari, and for each line item open a new tab, after enter the address press go

1. http://123tramites.com
2. http://infoquiz.net
3. http://statsupplier.com
4. http://redirstats.com
5. http://statsads.co
6. http://nnews.co
7. http://adsmetrics.co
8. take an encrypted backup
9. use mvt to decrypt
10. use mvt to check the backup

### Result

MVT-Tool finds all 7 addresses to be positive for Pegasus without ever having an internet connection

[![Screen-Shot-2022-11-30-at-12-17-26-PM.png](https://i.postimg.cc/kGxCzF6q/Screen-Shot-2022-11-30-at-12-17-26-PM.png)](https://postimg.cc/BPQR1FBV)

### Prep
open safari, and for each line item open a new tab, after enter the address press go

1. http://123tramites.com
2. http://infoquiz.net
3. http://statsupplier.com
4. http://redirstats.com
5. http://statsads.co
6. http://nnews.co
7. http://adsmetrics.co
8. take an encrypted backup
9. use mvt to decrypt
10. use mvt to check the backup

### Result

MVT-Tool finds only 6 addresses to be positive for Pegasus. Because statsads.co redirected to 11165151.addotnet.com it was not recognized as a malicious IOC 

In [Appendix E](https://www.amnesty.org/en/latest/research/2021/08/appendix-e-pegasus-forensic-traces-per-target-identified-in-the-aftermath-of-the-revelations-of-pegasus-project/) of the Amnesty Verification report Jordi Sànchez had statsads.co that redirected as well, and when I ran the exact IOCs listed for Jordi in the report, there was no Pegasus detection found in the Safari History because of the redirects.

Jordi Sànchez
- https://statsads.co/SomI5j9B
- https://statsads.co/91EiQzIaP
- https://statsads.co/2B56JyXwZ

[![Screen-Shot-2022-11-30-at-11-52-57-AM.png](https://i.postimg.cc/yx6nC7Wx/Screen-Shot-2022-11-30-at-11-52-57-AM.png)](https://postimg.cc/WFK0MLGc)
### Conclusion

MVT-Tool is not using logic to make conclusions of a pegasus infection, it is only looking for strings, and having having an internet connection or not having an internet connection on the device affects the results. This is why MVT-Tool should have documentation showing the scenarios in which false positive results are possible. 

A person can manually enter any domain listed as malicious into their browser and MVT-Tool will pick it up as a positive infection when it is not.

**Comment by abashinfection** [comment]
If there are traces of C2 communication on my device, I want to be alerted. 
Whether I've manually inserted those traces or not. 

MVT-Tool is flagging those events as _suspicious_, and they have a disclaimer in their README stating _"This is not intended for end-user self-assessment"_, so no one is _blindly_ using a single suspicious event from MVT-Tool and proclaiming infection.


Now, let's get to the part where MVT-Tool reports differ based on connectivity. 
iOS is a very closed OS and researchers are limited in what data they can extract, and even more limited in terms of configuration. It appears that Safari history does not track all redirects for a URL, but it simply logs the end URL. Most likely this behavior can't be configured and no additional data is available. 
Because of this, you are suggesting there could be FPs? Why would that be? 
It looks to me as if we are dealing with potential FNs rather than FPs. 
If a payload uses the redirected URL on a device with connectivity, no malicious event would be logged in Safari history. This is a potential FN, luckily there are many other IOCs provided by MVT-Tool that can be used to determine an infection verdict.  

> MVT-Tool is not using logic to make conclusions of a pegasus infection

Yes, this has been already told to you multiple times. 
Forensic tools are used as supporting tools during analyses. No one is claiming this tool *alone* will tell you have been infected or not. 
It's in the first line of their README: 

> Mobile Verification Toolkit (MVT) is a collection of utilities to simplify and automate the process of gathering forensic traces _helpful to identify a potential compromise_ of Android and iOS devices.

**Comment by ornaeric** [comment]
Jonathan, the fact you created this issue and what you are claiming is an issue only proves one thing. 

You lack the skills and knowledge to even be discussing the topic. Making ignorant statements and ignorant judgements doesn't help your case. You literally have no idea what you are talking about.
